// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYfN44fqgZ0nlzaLAXWIF8oxlLikFIYuw',
    appId: '1:323319251610:web:9228cb48647ad31250d523',
    messagingSenderId: '323319251610',
    projectId: 'sipao-ab14b',
    authDomain: 'sipao-ab14b.firebaseapp.com',
    storageBucket: 'sipao-ab14b.appspot.com',
    measurementId: 'G-GMH3BGB0V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZOHRoeH3sy0lUGXjImHSEd_jbIkoBsRk',
    appId: '1:323319251610:android:9d92624ee2397c8350d523',
    messagingSenderId: '323319251610',
    projectId: 'sipao-ab14b',
    storageBucket: 'sipao-ab14b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXGBUt6xi8dYzO0wf7_FCb67wZFxKiFsw',
    appId: '1:323319251610:ios:e503892ab1b2b99050d523',
    messagingSenderId: '323319251610',
    projectId: 'sipao-ab14b',
    storageBucket: 'sipao-ab14b.appspot.com',
    iosBundleId: 'com.example.sipao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXGBUt6xi8dYzO0wf7_FCb67wZFxKiFsw',
    appId: '1:323319251610:ios:b352d422f377b59b50d523',
    messagingSenderId: '323319251610',
    projectId: 'sipao-ab14b',
    storageBucket: 'sipao-ab14b.appspot.com',
    iosBundleId: 'com.example.sipao.RunnerTests',
  );
}
